# Generated by Django 5.1.6 on 2025-02-25 13:05

import django.db.models.deletion
import shortuuidfield.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movie', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('uid', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False, unique=True, verbose_name='用户唯一标识')),
                ('is_upgrade', models.IntegerField(default=0, verbose_name='是否升级会员')),
                ('upgrade_time', models.DateTimeField(blank=True, null=True, verbose_name='升级日期')),
                ('expire_time', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('upgrade_count', models.IntegerField(default=0, verbose_name='升级次数')),
                ('movies', models.ManyToManyField(to='movie.movie')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'db_table': 'profile',
            },
        ),
    ]
